### ISSUE TITLE
The FrameLayout overlaps other views  

### ISSUE THREAD

**Issue by AlexHuicu** [Tunous/SwipeActionView#12] opened 2017-09-11 13:55 UTC
Steps to reproduce:

First way
1.Swipe the item:
![screenshot_20170911-164749](https://user-images.githubusercontent.com/24639122/30277718-52de7e46-9711-11e7-8a27-7ed866a27127.png)
2.Open a simple alert dialog:
![screenshot_20170911-164809](https://user-images.githubusercontent.com/24639122/30278113-47db179c-9712-11e7-9f51-4375a0773af2.png)

Second way
1.Swipe the ListView:
![screenshot_20170911-164839](https://user-images.githubusercontent.com/24639122/30277905-d65c4186-9711-11e7-8c6e-864c1c42f95a.png)
2.Open a simple alert dialog:
![screenshot_20170911-164844](https://user-images.githubusercontent.com/24639122/30277912-df88aa10-9711-11e7-84bf-2fa94e599d8b.png)

The same behaviour occurs when you open a new activity and press back.

**Comment by AlexHuicu** [comment] 2017-09-11 14:17
Edit: 
It happens when tapping on the button, and not beacuse of the Dialog

**Comment by Tunous** [comment] 2017-09-11 14:33
Potential duplicate of #9 

Setting `app:sav_alwaysDrawBackground="true"` could work as a workaround. (You might have to give your container views a background after that)

I wasn't yet able to reproduce the original issue. But I'll try to fix it again with this new information. Thank you for details :D

**Comment by AlexHuicu** [comment] 2017-09-11 14:58
I can't find the 'app:sav_alwaysDrawBackground' property. My root view is currently RelativeLayout. I will try to use a CoordinatorLayout and see if the problem is solved

**Comment by Tunous** [comment] 2017-09-11 15:00
It's applied to `SwipeActionView`. Like here: https://github.com/Tunous/SwipeActionView/blob/master/sample/src/main/res/layout/activity_main.xml#L93

**Comment by AlexHuicu** [comment] 2017-09-11 15:05
That is a great hint :D

**Closed as completed** 2018-11-12 16:55 UTC
